name: Pass AWS Credentials to Docker

on:
  push:
    branches:
      - main

jobs:

  get-pass-aws-credentials:
    name: Get AWS Credentials and Pass to Docker
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACC_NO }}:role/aws-creds-docker-poc
          role-duration-seconds: 900
          aws-region: eu-central-1

      - name: echo AWS creds to a file
        run: |
          echo "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" >> docker.aws
          echo "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" >> docker.aws
          echo "AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}" >> docker.aws
          echo "AWS_REGION=$AWS_REGION" >> docker.aws

      - name: Run AWS CLI STS in Docker with env vars
        run: |
          docker run --rm -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
            -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
            -e AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN \
            -e AWS_REGION=$AWS_REGION \
            amazon/aws-cli sts get-caller-identity
      
      - name: Run AWS CLI STS in Docker with AWS creds file
        run: |
          docker run --rm --env-file docker.aws amazon/aws-cli sts get-caller-identity

      - name: Run AWS CLI w/o credentials
        run: |
          docker run --rm amazon/aws-cli sts get-caller-identity
      - run: echo ${{ fromJson('["self-hosted"]') }}
